source..=src/main/java/,\
          src/main/kotlin/,\
           src/main/resources/,\
           src/test/java/,\
           src/test/kotlin/,\
           src/test/resources/
bin.includes=META-INF/, .
