/**
 */
package org.palladiosimulator.blockchainsystems.bscm.linkallocation.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.palladiosimulator.blockchainsystems.bscm.linkallocation.util.LinkallocationAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class LinkallocationItemProviderAdapterFactory extends LinkallocationAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public LinkallocationItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocationRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkAllocationRepositoryItemProvider linkAllocationRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocationRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkAllocationRepositoryAdapter() {
		if (linkAllocationRepositoryItemProvider == null) {
			linkAllocationRepositoryItemProvider = new LinkAllocationRepositoryItemProvider(this);
		}

		return linkAllocationRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LinkAllocationItemProvider linkAllocationItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.LinkAllocation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLinkAllocationAdapter() {
		if (linkAllocationItemProvider == null) {
			linkAllocationItemProvider = new LinkAllocationItemProvider(this);
		}

		return linkAllocationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkLatencySpecificationValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DynamicLinkLatencySpecificationValueItemProvider dynamicLinkLatencySpecificationValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkLatencySpecificationValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDynamicLinkLatencySpecificationValueAdapter() {
		if (dynamicLinkLatencySpecificationValueItemProvider == null) {
			dynamicLinkLatencySpecificationValueItemProvider = new DynamicLinkLatencySpecificationValueItemProvider(
					this);
		}

		return dynamicLinkLatencySpecificationValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkThroughputSpecificationValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DynamicLinkThroughputSpecificationValueItemProvider dynamicLinkThroughputSpecificationValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkThroughputSpecificationValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDynamicLinkThroughputSpecificationValueAdapter() {
		if (dynamicLinkThroughputSpecificationValueItemProvider == null) {
			dynamicLinkThroughputSpecificationValueItemProvider = new DynamicLinkThroughputSpecificationValueItemProvider(
					this);
		}

		return dynamicLinkThroughputSpecificationValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkLatencySpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DynamicLinkLatencySpecificationItemProvider dynamicLinkLatencySpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkLatencySpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDynamicLinkLatencySpecificationAdapter() {
		if (dynamicLinkLatencySpecificationItemProvider == null) {
			dynamicLinkLatencySpecificationItemProvider = new DynamicLinkLatencySpecificationItemProvider(this);
		}

		return dynamicLinkLatencySpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkThroughputSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DynamicLinkThroughputSpecificationItemProvider dynamicLinkThroughputSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.DynamicLinkThroughputSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDynamicLinkThroughputSpecificationAdapter() {
		if (dynamicLinkThroughputSpecificationItemProvider == null) {
			dynamicLinkThroughputSpecificationItemProvider = new DynamicLinkThroughputSpecificationItemProvider(this);
		}

		return dynamicLinkThroughputSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.StaticLinkLatencySpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticLinkLatencySpecificationItemProvider staticLinkLatencySpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.StaticLinkLatencySpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticLinkLatencySpecificationAdapter() {
		if (staticLinkLatencySpecificationItemProvider == null) {
			staticLinkLatencySpecificationItemProvider = new StaticLinkLatencySpecificationItemProvider(this);
		}

		return staticLinkLatencySpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.StaticLinkThroughputSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StaticLinkThroughputSpecificationItemProvider staticLinkThroughputSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.linkallocation.StaticLinkThroughputSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStaticLinkThroughputSpecificationAdapter() {
		if (staticLinkThroughputSpecificationItemProvider == null) {
			staticLinkThroughputSpecificationItemProvider = new StaticLinkThroughputSpecificationItemProvider(this);
		}

		return staticLinkThroughputSpecificationItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (linkAllocationRepositoryItemProvider != null)
			linkAllocationRepositoryItemProvider.dispose();
		if (linkAllocationItemProvider != null)
			linkAllocationItemProvider.dispose();
		if (dynamicLinkLatencySpecificationValueItemProvider != null)
			dynamicLinkLatencySpecificationValueItemProvider.dispose();
		if (dynamicLinkThroughputSpecificationValueItemProvider != null)
			dynamicLinkThroughputSpecificationValueItemProvider.dispose();
		if (dynamicLinkLatencySpecificationItemProvider != null)
			dynamicLinkLatencySpecificationItemProvider.dispose();
		if (dynamicLinkThroughputSpecificationItemProvider != null)
			dynamicLinkThroughputSpecificationItemProvider.dispose();
		if (staticLinkLatencySpecificationItemProvider != null)
			staticLinkLatencySpecificationItemProvider.dispose();
		if (staticLinkThroughputSpecificationItemProvider != null)
			staticLinkThroughputSpecificationItemProvider.dispose();
	}

}
