/**
 */
package org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.util.P2pnetworkAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class P2pnetworkItemProviderAdapterFactory extends P2pnetworkAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public P2pnetworkItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.P2PNetwork} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected P2PNetworkItemProvider p2PNetworkItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.P2PNetwork}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createP2PNetworkAdapter() {
		if (p2PNetworkItemProvider == null) {
			p2PNetworkItemProvider = new P2PNetworkItemProvider(this);
		}

		return p2PNetworkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.ExplicitNetworkTopology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExplicitNetworkTopologyItemProvider explicitNetworkTopologyItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.ExplicitNetworkTopology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExplicitNetworkTopologyAdapter() {
		if (explicitNetworkTopologyItemProvider == null) {
			explicitNetworkTopologyItemProvider = new ExplicitNetworkTopologyItemProvider(this);
		}

		return explicitNetworkTopologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.Node} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NodeItemProvider nodeItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.Node}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNodeAdapter() {
		if (nodeItemProvider == null) {
			nodeItemProvider = new NodeItemProvider(this);
		}

		return nodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.ConnectedSubgraphsNetworkTopology} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConnectedSubgraphsNetworkTopologyItemProvider connectedSubgraphsNetworkTopologyItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.ConnectedSubgraphsNetworkTopology}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConnectedSubgraphsNetworkTopologyAdapter() {
		if (connectedSubgraphsNetworkTopologyItemProvider == null) {
			connectedSubgraphsNetworkTopologyItemProvider = new ConnectedSubgraphsNetworkTopologyItemProvider(this);
		}

		return connectedSubgraphsNetworkTopologyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphSpecification} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubgraphSpecificationItemProvider subgraphSpecificationItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphSpecification}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubgraphSpecificationAdapter() {
		if (subgraphSpecificationItemProvider == null) {
			subgraphSpecificationItemProvider = new SubgraphSpecificationItemProvider(this);
		}

		return subgraphSpecificationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubgraphLinkItemProvider subgraphLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubgraphLinkAdapter() {
		if (subgraphLinkItemProvider == null) {
			subgraphLinkItemProvider = new SubgraphLinkItemProvider(this);
		}

		return subgraphLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphNodeTemplate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SubgraphNodeTemplateItemProvider subgraphNodeTemplateItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.SubgraphNodeTemplate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSubgraphNodeTemplateAdapter() {
		if (subgraphNodeTemplateItemProvider == null) {
			subgraphNodeTemplateItemProvider = new SubgraphNodeTemplateItemProvider(this);
		}

		return subgraphNodeTemplateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.BidirectionalLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BidirectionalLinkItemProvider bidirectionalLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.BidirectionalLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBidirectionalLinkAdapter() {
		if (bidirectionalLinkItemProvider == null) {
			bidirectionalLinkItemProvider = new BidirectionalLinkItemProvider(this);
		}

		return bidirectionalLinkItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.UnidirectionalLink} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UnidirectionalLinkItemProvider unidirectionalLinkItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.blockchainsystems.bscm.p2pnetwork.UnidirectionalLink}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUnidirectionalLinkAdapter() {
		if (unidirectionalLinkItemProvider == null) {
			unidirectionalLinkItemProvider = new UnidirectionalLinkItemProvider(this);
		}

		return unidirectionalLinkItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (p2PNetworkItemProvider != null)
			p2PNetworkItemProvider.dispose();
		if (explicitNetworkTopologyItemProvider != null)
			explicitNetworkTopologyItemProvider.dispose();
		if (nodeItemProvider != null)
			nodeItemProvider.dispose();
		if (connectedSubgraphsNetworkTopologyItemProvider != null)
			connectedSubgraphsNetworkTopologyItemProvider.dispose();
		if (subgraphSpecificationItemProvider != null)
			subgraphSpecificationItemProvider.dispose();
		if (subgraphLinkItemProvider != null)
			subgraphLinkItemProvider.dispose();
		if (subgraphNodeTemplateItemProvider != null)
			subgraphNodeTemplateItemProvider.dispose();
		if (bidirectionalLinkItemProvider != null)
			bidirectionalLinkItemProvider.dispose();
		if (unidirectionalLinkItemProvider != null)
			unidirectionalLinkItemProvider.dispose();
	}

}
