#

pluginName = org.palladiosimulator.blockchainsystems.bscm Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_NodeAllocation_type = Node Allocation
_UI_NodeAllocationRepository_type = Node Allocation Repository
_UI_NodeAllocationContext_type = Node Allocation Context
_UI_BlockchainSystemNodeSystem_type = Blockchain System Node System
_UI_BlockchainSystemNodeAssemblyContext_type = Blockchain System Node Assembly Context
_UI_NodeBehaviorSpecification_type = Node Behavior Specification
_UI_BlockchainSystemNodeComponent_type = Blockchain System Node Component
_UI_BlockchainSystemNodeComponentRepository_type = Blockchain System Node Component Repository
_UI_BlockValidatorComponent_type = Block Validator Component
_UI_MiningProcessComponent_type = Mining Process Component
_UI_BlockValiationDurationSpecification_type = Block Valiation Duration Specification
_UI_BlockValidationDurationValue_type = Block Validation Duration Value
_UI_P2PNetwork_type = P2P Network
_UI_NetworkTopology_type = Network Topology
_UI_ExplicitNetworkTopology_type = Explicit Network Topology
_UI_ConstraintNetworkTopology_type = Constraint Network Topology
_UI_Node_type = Node
_UI_Link_type = Link
_UI_ConnectedSubgraphsNetworkTopology_type = Connected Subgraphs Network Topology
_UI_SubgraphSpecification_type = Subgraph Specification
_UI_ConnectivitySpecification_type = Connectivity Specification
_UI_SubgraphLink_type = Subgraph Link
_UI_SubgraphNodeTemplate_type = Subgraph Node Template
_UI_BidirectionalLink_type = Bidirectional Link
_UI_UnidirectionalLink_type = Unidirectional Link
_UI_BlockchainSystem_type = Blockchain System
_UI_BlockchainSystemSpecification_type = Blockchain System Specification
_UI_NodeEnvironment_type = Node Environment
_UI_NodeResourceContainer_type = Node Resource Container
_UI_GeographicalRegionsSpecification_type = Geographical Regions Specification
_UI_GeographicalRegion_type = Geographical Region
_UI_LinkAllocationRepository_type = Link Allocation Repository
_UI_LinkAllocation_type = Link Allocation
_UI_LinkLatencySpecification_type = Link Latency Specification
_UI_BandwidthSpecification_type = Bandwidth Specification
_UI_DynamicLinkLatencySpecificationValue_type = Dynamic Link Latency Specification Value
_UI_LinkThroughputSpecification_type = Link Throughput Specification
_UI_DynamicLinkThroughputSpecificationValue_type = Dynamic Link Throughput Specification Value
_UI_DynamicLinkLatencySpecification_type = Dynamic Link Latency Specification
_UI_DynamicLinkThroughputSpecification_type = Dynamic Link Throughput Specification
_UI_StaticLinkLatencySpecification_type = Static Link Latency Specification
_UI_StaticLinkThroughputSpecification_type = Static Link Throughput Specification
_UI_TransactionsSpecification_type = Specification
_UI_TransactionPropertiesSpecification_type = Transaction Properties Specification
_UI_TransactionPropertiesSpecificationValue_type = Transaction Properties Specification Value
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_NodeAllocation_AllocationContexts_feature = Allocation Contexts
_UI_NodeAllocation_NodeAllocationEnvironment_feature = Node Allocation Environment
_UI_NodeAllocation_NodeSystem_feature = Node System
_UI_NodeAllocation_GeographicalRegion_feature = Geographical Region
_UI_NodeAllocationRepository_NodeAllocations_feature = Node Allocations
_UI_NodeAllocationContext_AssemblyContext_feature = Assembly Context
_UI_NodeAllocationContext_ResourceContainer_feature = Resource Container
_UI_BlockchainSystemNodeSystem_MiningProcessAssembly_feature = Mining Process Assembly
_UI_BlockchainSystemNodeSystem_BlockValidatorAssembly_feature = Block Validator Assembly
_UI_BlockchainSystemNodeSystem_AssemblyContexts_feature = Assembly Contexts
_UI_BlockchainSystemNodeSystem_Behavior_feature = Behavior
_UI_BlockchainSystemNodeAssemblyContext_EncapsulatedComponent_feature = Encapsulated Component
_UI_NodeBehaviorSpecification_Behavior_feature = Behavior
_UI_BlockchainSystemNodeComponentRepository_Components_feature = Components
_UI_BlockValidatorComponent_ValidationDuration_feature = Validation Duration
_UI_BlockValidatorComponent_crashed_feature = Crashed
_UI_MiningProcessComponent_IsMiningProcessEnabled_feature = Is Mining Process Enabled
_UI_BlockValiationDurationSpecification_Values_feature = Values
_UI_BlockValidationDurationValue_Duration_feature = Duration
_UI_BlockValidationDurationValue_Probability_feature = Probability
_UI_P2PNetwork_Topology_feature = Topology
_UI_ExplicitNetworkTopology_Nodes_feature = Nodes
_UI_ExplicitNetworkTopology_Links_feature = Links
_UI_Node_Allocation_feature = Allocation
_UI_Link_Allocation_feature = Allocation
_UI_ConnectedSubgraphsNetworkTopology_Subgraphs_feature = Subgraphs
_UI_ConnectedSubgraphsNetworkTopology_SubgraphLinks_feature = Subgraph Links
_UI_SubgraphSpecification_NodeTemplates_feature = Node Templates
_UI_SubgraphSpecification_Connectivity_feature = Connectivity
_UI_SubgraphSpecification_LinkAllocation_feature = Link Allocation
_UI_SubgraphSpecification_ConnectivitySpecification_feature = Connectivity Specification
_UI_ConnectivitySpecification_InBoundLinkAllocationSpecification_feature = In Bound Link Allocation Specification
_UI_ConnectivitySpecification_OutBoundLinkAllocationSpecification_feature = Out Bound Link Allocation Specification
_UI_ConnectivitySpecification_NumberOfInbound_feature = Number Of Inbound
_UI_ConnectivitySpecification_NumberOfOutBound_feature = Number Of Out Bound
_UI_SubgraphLink_Allocation_feature = Allocation
_UI_SubgraphLink_ConnectedSubgraphs_feature = Connected Subgraphs
_UI_SubgraphNodeTemplate_NumberOfNodeOccurences_feature = Number Of Node Occurences
_UI_SubgraphNodeTemplate_Allocation_feature = Allocation
_UI_SubgraphNodeTemplate_IsSubgraphProxy_feature = Is Subgraph Proxy
_UI_BidirectionalLink_ConnectedNodes_feature = Connected Nodes
_UI_UnidirectionalLink_FromNode_feature = From Node
_UI_UnidirectionalLink_ToNode_feature = To Node
_UI_BlockchainSystem_Network_feature = Network
_UI_BlockchainSystem_Specification_feature = Specification
_UI_BlockchainSystem_TransactionsSpecification_feature = Transactions Specification
_UI_BlockchainSystem_GeographicalRegionsSpecification_feature = Geographical Regions Specification
_UI_BlockchainSystemSpecification_MeanBlockTime_feature = Mean Block Time
_UI_BlockchainSystemSpecification_NumOfRequiredSecurityConfirmations_feature = Num Of Required Security Confirmations
_UI_BlockchainSystemSpecification_MaxBlockSize_feature = Max Block Size
_UI_BlockchainSystemSpecification_BlockReward_feature = Block Reward
_UI_BlockchainSystemSpecification_HashRateConcentration_feature = Hash Rate Concentration
_UI_BlockchainSystemSpecification_NumberOfAttacker_feature = Number Of Attacker
_UI_NodeEnvironment_ResourceContainers_feature = Resource Containers
_UI_NodeResourceContainer_ResourcePower_feature = Resource Power
_UI_GeographicalRegionsSpecification_Regions_feature = Regions
_UI_GeographicalRegion_RegionName_feature = Region Name
_UI_LinkAllocationRepository_LinkAllocations_feature = Link Allocations
_UI_LinkAllocation_latencySpecification_feature = Latency Specification
_UI_LinkAllocation_throughputSpecification_feature = Throughput Specification
_UI_LinkAllocation_bandwidthSpecification_feature = Bandwidth Specification
_UI_BandwidthSpecification_Bandwidth_feature = Bandwidth
_UI_BandwidthSpecification_HeterogeneityLinkTarget_feature = Heterogeneity Link Target
_UI_BandwidthSpecification_HeterogeneityNodeTarget_feature = Heterogeneity Node Target
_UI_DynamicLinkLatencySpecificationValue_Latency_feature = Latency
_UI_DynamicLinkLatencySpecificationValue_Probability_feature = Probability
_UI_DynamicLinkLatencySpecificationValue_Duration_feature = Duration
_UI_DynamicLinkThroughputSpecificationValue_Throughput_feature = Throughput
_UI_DynamicLinkThroughputSpecificationValue_Probability_feature = Probability
_UI_DynamicLinkThroughputSpecificationValue_Duration_feature = Duration
_UI_DynamicLinkLatencySpecification_Values_feature = Values
_UI_DynamicLinkThroughputSpecification_Values_feature = Values
_UI_StaticLinkLatencySpecification_Latency_feature = Latency
_UI_StaticLinkThroughputSpecification_Throughput_feature = Throughput
_UI_TransactionsSpecification_MeanTransactionCreationInterval_feature = Mean Transaction Creation Interval
_UI_TransactionsSpecification_TransactionPropertiesSpecification_feature = Transaction Properties Specification
_UI_TransactionPropertiesSpecification_Values_feature = Values
_UI_TransactionPropertiesSpecificationValue_Size_feature = Size
_UI_TransactionPropertiesSpecificationValue_Fee_feature = Fee
_UI_TransactionPropertiesSpecificationValue_Probability_feature = Probability
_UI_TransactionPropertiesSpecificationValue_Amount_feature = Amount
_UI_Unknown_feature = Unspecified

_UI_NodeBehavior_Honest_literal = Honest
_UI_NodeBehavior_Malicious_literal = Malicious
