#

pluginName = org.palladiosimulator.blockchainsystems.bscm Editor
providerName = www.example.org

_UI_NodeallocationEditor_menu = &Nodeallocation Editor
_UI_NodesystemEditor_menu = &Nodesystem Editor
_UI_BlockchainsystemComponentRepositoryEditor_menu = &BlockchainsystemComponentRepository Editor
_UI_P2pnetworkEditor_menu = &P2pnetwork Editor
_UI_BlockchainsystemEditor_menu = &Blockchainsystem Editor
_UI_NodeenvironmentEditor_menu = &Nodeenvironment Editor
_UI_GeographicalregionsEditor_menu = &Geographicalregions Editor
_UI_LinkallocationEditor_menu = &Linkallocation Editor
_UI_TransactionsEditor_menu = &Transactions Editor

_UI_CreateChild_menu_item = &New Child
_UI_CreateSibling_menu_item = N&ew Sibling

_UI_ShowPropertiesView_menu_item = Show &Properties View
_UI_RefreshViewer_menu_item = &Refresh

_UI_SelectionPage_label = Selection
_UI_ParentPage_label = Parent
_UI_ListPage_label = List
_UI_TreePage_label = Tree
_UI_TablePage_label = Table
_UI_TreeWithColumnsPage_label = Tree with Columns
_UI_ObjectColumn_label = Object
_UI_SelfColumn_label = Self

_UI_NoObjectSelected = Selected Nothing
_UI_SingleObjectSelected = Selected Object: {0}
_UI_MultiObjectSelected = Selected {0} Objects

_UI_OpenEditorError_label = Open Editor

_UI_Wizard_category = Example EMF Model Creation Wizards

_UI_CreateModelError_message = Problems encountered in file "{0}"

_UI_NodeallocationModelWizard_label = Nodeallocation Model
_UI_NodeallocationModelWizard_description = Create a new Nodeallocation model

_UI_NodeallocationEditor_label = Nodeallocation Model Editor

_UI_NodeallocationEditorFilenameDefaultBase = My
_UI_NodeallocationEditorFilenameExtensions = nodeallocation

_UI_NodesystemModelWizard_label = Nodesystem Model
_UI_NodesystemModelWizard_description = Create a new Nodesystem model

_UI_NodesystemEditor_label = Nodesystem Model Editor

_UI_NodesystemEditorFilenameDefaultBase = My
_UI_NodesystemEditorFilenameExtensions = nodesystem

_UI_BlockchainsystemComponentRepositoryModelWizard_label = BlockchainsystemComponentRepository Model
_UI_BlockchainsystemComponentRepositoryModelWizard_description = Create a new BlockchainsystemComponentRepository model

_UI_BlockchainsystemComponentRepositoryEditor_label = BlockchainsystemComponentRepository Model Editor

_UI_BlockchainsystemComponentRepositoryEditorFilenameDefaultBase = My
_UI_BlockchainsystemComponentRepositoryEditorFilenameExtensions = bscmrepository

_UI_P2pnetworkModelWizard_label = P2pnetwork Model
_UI_P2pnetworkModelWizard_description = Create a new P2pnetwork model

_UI_P2pnetworkEditor_label = P2pnetwork Model Editor

_UI_P2pnetworkEditorFilenameDefaultBase = My
_UI_P2pnetworkEditorFilenameExtensions = p2pnetwork

_UI_BlockchainsystemModelWizard_label = Blockchainsystem Model
_UI_BlockchainsystemModelWizard_description = Create a new Blockchainsystem model

_UI_BlockchainsystemEditor_label = Blockchainsystem Model Editor

_UI_BlockchainsystemEditorFilenameDefaultBase = My
_UI_BlockchainsystemEditorFilenameExtensions = blockchainsystem

_UI_NodeenvironmentModelWizard_label = Nodeenvironment Model
_UI_NodeenvironmentModelWizard_description = Create a new Nodeenvironment model

_UI_NodeenvironmentEditor_label = Nodeenvironment Model Editor

_UI_NodeenvironmentEditorFilenameDefaultBase = My
_UI_NodeenvironmentEditorFilenameExtensions = nodeenvironment

_UI_GeographicalregionsModelWizard_label = Geographicalregions Model
_UI_GeographicalregionsModelWizard_description = Create a new Geographicalregions model

_UI_GeographicalregionsEditor_label = Geographicalregions Model Editor

_UI_GeographicalregionsEditorFilenameDefaultBase = My
_UI_GeographicalregionsEditorFilenameExtensions = geographicalregions

_UI_LinkallocationModelWizard_label = Linkallocation Model
_UI_LinkallocationModelWizard_description = Create a new Linkallocation model

_UI_LinkallocationEditor_label = Linkallocation Model Editor

_UI_LinkallocationEditorFilenameDefaultBase = My
_UI_LinkallocationEditorFilenameExtensions = linkallocation

_UI_TransactionsModelWizard_label = Transactions Model
_UI_TransactionsModelWizard_description = Create a new Transactions model

_UI_TransactionsEditor_label = Transactions Model Editor

_UI_TransactionsEditorFilenameDefaultBase = My
_UI_TransactionsEditorFilenameExtensions = transactions

_UI_Wizard_label = New

_WARN_FilenameExtension = The file name must end in ''.{0}''
_WARN_FilenameExtensions = The file name must have one of the following extensions: {0}

_UI_ModelObject = &Model Object
_UI_XMLEncoding = &XML Encoding
_UI_XMLEncodingChoices = UTF-8 ASCII UTF-16 UTF-16BE UTF-16LE ISO-8859-1
_UI_Wizard_initial_object_description = Select a model object to create

_UI_FileConflict_label = File Conflict
_WARN_FileConflict = There are unsaved changes that conflict with changes made outside the editor.  Do you wish to discard this editor's changes?

